spring:
  application:
    name: producer-service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      batch-size: 32768 # bytes
      compression-type: snappy
      retries: 10_000
      buffer-memory: 33554432 #32 Mb
      properties:
        linger.ms: 100
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

