spring:
  application:
    name: consumer-user-messages-1
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: user-message-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

  datasource:
    url: jdbc:postgresql://localhost:15432/consumer_1
    username: app_1
    password: app_1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC